-- Schéma de base de données pour l'application de recettes

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE recipes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    ingredients TEXT NOT NULL,
    steps TEXT NOT NULL,
    category_id INT,
    prep_time INT,
    cook_time INT,
    difficulty ENUM('Facile','Moyenne','Difficile'),
    image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE favorites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    recipe_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (recipe_id) REFERENCES recipes(id)
);

CREATE TABLE comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    recipe_id INT NOT NULL,
    content TEXT NOT NULL,
    rating INT CHECK (rating >= 1 AND rating <= 5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (recipe_id) REFERENCES recipes(id)
);

CREATE TABLE recipe_ingredients (
    recipe_id INT NOT NULL,
    ingredient_id INT NOT NULL,
    quantity VARCHAR(50),
    unit VARCHAR(30),
    PRIMARY KEY (recipe_id, ingredient_id),
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE CASCADE
);

-- Ingrédients courants
INSERT INTO ingredients (name) VALUES
('Sel'),
('Poivre'),
('Sucre'),
('Farine'),
('Beurre'),
('Huile d\'olive'),
('Oeuf'),
('Lait'),
('Crème fraîche'),
('Levure'),
('Eau'),
('Ail'),
('Oignon'),
('Tomate'),
('Carotte'),
('Pommes de terre'),
('Riz'),
('Pâtes'),
('Pain'),
('Fromage'),
('Jambon'),
('Poulet'),
('Boeuf'),
('Porc'),
('Poisson'),
('Thon'),
('Saumon'),
('Crevettes'),
('Citron'),
('Basilic'),
('Persil'),
('Thym'),
('Laurier'),
('Romarin'),
('Coriandre'),
('Cumin'),
('Curry'),
('Paprika'),
('Moutarde'),
('Vinaigre'),
('Champignon'),
('Courgette'),
('Aubergine'),
('Poivron'),
('Épinard'),
('Petits pois'),
('Haricots verts'),
('Maïs'),
('Lentilles'),
('Yaourt'),
('Chocolat'),
('Vanille'),
('Noix'),
('Amande'),
('Noisette'),
('Raisin'),
('Pomme'),
('Poire'),
('Banane'),
('Orange'),
('Fraise'),
('Framboise'),
('Miel'),
('Saucisse'),
('Lardons'),
('Saumon fumé'),
('Dinde'),
('Agneau'),
('Veau'),
('Mouton'),
('Escalope'),
('Creme liquide'),
('Piment'),
('Gingembre'),
('Cannelle'),
('Clou de girofle'),
('Cardamome'),
('Safran'),
('Aneth'),
('Menthe'),
('Olive'),
('Courge'),
('Betterave'),
('Radis'),
('Navet'),
('Chou'),
('Brocoli'),
('Chou-fleur'),
('Poireau'),
('Endive'),
('Salade'),
('Roquette'),
('Avocat'),
('Mangue'),
('Ananas'),
('Abricot'),
('Cerise'),
('Prune'),
('Figues'),
('Dattes'),
('Kiwis'),
('Grenade'),
('Câpres'),
('Cornichon'),
('Tabasco'),
('Sauce soja'),
('Sauce tomate'),
('Bouillon'),
('Crabe'),
('Homard'),
('Moules'),
('Saint-Jacques'),
('Calamar'),
('Tofu'),
('Seitan'),
('Lait de coco'),
('Noix de coco'),
('Sésame'),
('Pistache'),
('Pignon'),
('Pain de mie'),
('Baguette'),
('Bière'),
('Vin blanc'),
('Vin rouge'),
('Champagne'),
('Rhum'),
('Whisky'),
('Vodka'),
('Tequila');

('Plat'),
('Dessert');

INSERT INTO recipes (user_id, title, description, ingredients, steps, category_id, prep_time, cook_time, difficulty, image) VALUES
(1, 'Quiche Lorraine', 'Une délicieuse quiche traditionnelle.', 'Pâte brisée, lardons, œufs, crème, gruyère', '1. Préchauffer le four... 2. Mélanger... 3. Cuire...', 2, 20, 40, 'Moyenne', NULL),
(2, 'Tiramisu', 'Dessert italien au café.', 'Biscuits, café, mascarpone, œufs, sucre, cacao', '1. Séparer les blancs... 2. Monter la crème... 3. Monter le tiramisu...', 3, 30, 0, 'Facile', NULL);

INSERT INTO favorites (user_id, recipe_id) VALUES
(1, 2),
(2, 1);

INSERT INTO comments (user_id, recipe_id, content, rating) VALUES
(1, 2, 'Excellent dessert, très facile à faire !', 5),
(2, 1, 'Recette savoureuse, ma famille a adoré.', 4);
